[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
CLUSTER_NAME = "kotor"
CONTROL_PLANE_IP = "192.168.20.201 192.168.20.202 192.168.20.203"
ENDPOINT = "kotor.tebbenet.nl"
DISK_NAME = "sda"
BWS_PROJECT_ID = "582cc0c9-2762-4769-9a35-b4da00ebcc1b"
BWS_SERVER_URL = "https://vault.bitwarden.com"

[tools]
github-cli = "2.102.0"
jq = "1.8.2"
yq = "4.54.1"
k9s = "0.51.0"
talosctl = "1.14.1"
kubectl = "1.37.1"
kustomize = "5.8.1"
helm = "4.3.0"
helmfile = "1.8.1"
kubeconform = "0.8.0"
cilium-cli = "0.20.1"
flux2 = "2.9.5"
"github:postfinance/topf" = "v0.6.0"        # Talhelper replacement
